mashup-service:
  links:
    - quote-service
    - swapi-proxy
    - zipkin-query
  environment:
    - SRAI_MICRO_SERVICE_SWAPI-PROXY_URL=http://swapi-proxy:8080/
    - SRAI_MICRO_SERVICE_QUOTE-SERVICE_URL=http://quote-service:4567/
#    - SRAI_MICRO_SERVICE_QUOTE-SERVICE_URL=http://172.17.0.1:4567/
    - SPRING_ZIPKIN_BASE-URL=http://zipkin-query:9411
    - SPRING_SLEUTH_SAMLPER_PERCENTAGE=1.0

quote-service:
  links:
    - zipkin-query
  environment:
    - ZIPKIN_QUERY_URL=http://zipkin-query:9411
    - ZIPKIN_SAMPLE_RATE=1.0

swapi-proxy:
  links:
    - redis
    - zipkin-query
  environment:
    - SPRING_ZIPKIN_BASE-URL=http://zipkin-query:9411
    - SPRING_SLEUTH_SAMLPER_PERCENTAGE=1.0

zipkin-storage:
  image: openzipkin/zipkin-mysql:1.4.0
  ports:
    - 3306:3306

zipkin-query:
  image: openzipkin/zipkin:1.4.0
  environment:
    - SELF_TRACING_ENABLED=false
    - STORAGE_TYPE=mysql
    - QUERY_LOG_LEVEL=INFO
    # Point the zipkin at the storage backend
    - MYSQL_HOST=zipkin-storage
  ports:
    # Listen port for the Scribe transport
    - 9410:9410
    # Historical port used for the Zipkin HTTP Api
    - 9411:9411
    # Zipkin UI used to be on a separate process listening on port 8080
    - 8081:9411
  links:
    - zipkin-storage
