mashup-service:
  build: ./microservices/core/mashup-service/.
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
    - ./microservices/core/mashup-service/build/libs:/build
  links:
    - quote-service
    - swapi-proxy
  environment:
    - SRAI_MICRO_SERVICE_SWAPI-PROXY_URL=http://swapi-proxy:8080/
    - SRAI_MICRO_SERVICE_QUOTE-SERVICE_URL=http://quote-service:4567/
#    - SRAI_MICRO_SERVICE_QUOTE-SERVICE_URL=http://172.17.0.1:4567/
    - SPRING_ZIPKIN_BASE-URL=http://zipkin-query:9411
    - SPRING_SLEUTH_SAMLPER_PERCENTAGE=0
  ports:
    - "8083:8080"

quote-service:
  build: ./microservices/core/quote-service/.
  hostname: quote-service
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
    - ./microservices/core/quote-service:/build
  environment:
    - ZIPKIN_QUERY_URL=http://zipkin-query:9411
    - ZIPKIN_SAMPLE_RATE=0
  ports:
    - "4567:4567"

swapi-proxy:
  build: ./microservices/core/swapi-proxy/.
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
    - ./microservices/core/swapi-proxy/build/libs:/build
  links:
    - redis
  environment:
    - SPRING_ZIPKIN_BASE-URL=http://zipkin-query:9411
    - SPRING_SLEUTH_SAMLPER_PERCENTAGE=0
  ports:
    - "8080:8080"

redis:
  image: redis:3.2.0-alpine
  ports:
    - "6379:6379"
