mashup-service:
  build: ./microservices/core/mashup-service/.
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
    - ./microservices/core/mashup-service/build/libs:/build
  links:
    - quote-service
    - swapi-proxy
    - zipkin-query
  environment:
    - SRAI_MICRO_SERVICE_SWAPI-PROXY_URL=http://swapi-proxy:8080/
    - SRAI_MICRO_SERVICE_QUOTE-SERVICE_URL=http://quote-service:4567/
    - SPRING_ZIPKIN_BASE-URL=http://zipkin-query:9411
    - SPRING_SLEUTH_SAMLPER_PERCENTAGE=1.0
  ports:
    - "8083:8080"
  log_driver: gelf
  log_opt:
    gelf-address: udp://${DOCKER_HOST_IP}:12201

quote-service:
  build: ./microservices/core/quote-service/.
  hostname: quote-service
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
    - ./microservices/core/quote-service:/build
  links:
    - zipkin-query
  environment:
    - ZIPKIN_QUERY_URL=http://zipkin-query:9411
    - ZIPKIN_SAMPLE_RATE=1.0
  ports:
    - "4567:4567"
  log_driver: gelf
  log_opt:
    gelf-address: udp://${DOCKER_HOST_IP}:12201

swapi-proxy:
  build: ./microservices/core/swapi-proxy/.
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
    - ./microservices/core/swapi-proxy/build/libs:/build
  links:
    - redis
    - zipkin-query
  environment:
    - SPRING_ZIPKIN_BASE-URL=http://zipkin-query:9411
    - SPRING_SLEUTH_SAMLPER_PERCENTAGE=1.0
  ports:
    - "8080:8080"
  log_driver: gelf
  log_opt:
    gelf-address: udp://${DOCKER_HOST_IP}:12201

redis:
  image: redis:3.2.0-alpine
  ports:
    - "6379:6379"

zipkin-storage:
  image: openzipkin/zipkin-mysql:1.1.4
  ports:
    - 3306:3306

zipkin-query:
  image: openzipkin/zipkin:1.1.4
  environment:
    # Uncomment to disable self-tracing
    # - SELF_TRACING_ENABLED=false
    - STORAGE_TYPE=mysql
    - QUERY_LOG_LEVEL=INFO
    # Point the zipkin at the storage backend
    - MYSQL_HOST=zipkin-storage
  ports:
    # Listen port for the Scribe transport
    - 9410:9410
    # Historical port used for the Zipkin HTTP Api
    - 9411:9411
    # Zipkin UI used to be on a separate process listening on port 8080
    - 8081:9411
  links:
    - zipkin-storage

probe:
  image: weaveworks/scope:0.15.0
  net: "host"
  pid: "host"
  privileged: true
  environment:
    CHECKPOINT_DISABLE: "true"
  labels:
    - "works.weave.role=system"
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock:rw"
  command:
    - "--probe.docker"
    - "true"

cadvisor:
  image: google/cadvisor:v0.23.2
  volumes:
    - "/:/rootfs:ro"
    - "/var/run:/var/run:rw"
    - "/sys:/sys:ro"
    - "/var/lib/docker/:/var/lib/docker:ro"
  ports:
    - "8082:8080"
  labels:
    - "name=cAdvisor"
    - "description=Google Container Advisor collects metrics from host and containers"
    - "version=latest"
