person-service:
  build: ./microservices/core/person-service/.
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
    - ./microservices/core/person-service/build/libs:/build
  links:
    - person-service-redis
  ports:
    - "8080:8080"
  log_driver: gelf
  log_opt:
    gelf-address: udp://${DOCKER_HOST_IP}:12201

person-service-redis:
  image: redis:3.2.0-alpine
  ports:
    - "6379:6379"


probe:
  image: weaveworks/scope:0.13.1
  net: "host"
  pid: "host"
  privileged: true
  environment:
    CHECKPOINT_DISABLE: "true"
  labels:
    - "works.weave.role=system"
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock:rw"
  command:
    - "--probe.docker"
    - "true"
