info:
  build:
    name: "${name}"
    description: "${description}"
    version: "${version}"
    created_at: "${new Date()}"
     
spring:
  redis:
    host: redis
  sleuth:
    feign:
      enabled: true
    sampler:
      percentage: 1
  zipkin:
    base-url: http://zipkin-query:9411 

feign:
  httpclient:
    enabled: true

logging:
  level:
    org.springframework.web: DEBUG
    srai.micro.service.services.SwapiService: DEBUG
    org.apache.http: DEBUG
    org.apache.http.wire: ERROR
