info:
  build:
    name: "${name}"
    description: "${description}"
    version: "${version}"
    created_at: "${new Date()}"
     
spring:
  redis:
    host: person-service-redis
    
logging.level.srai.micro.service.services.SwapiService: DEBUG